version: "3.6"
services:
  hc_alpha-postgres:
    image: postgres
    hostname: hc_alpha-postgres
    restart: unless-stopped
    container_name: hc_alpha-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER-postgres}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    depends_on:
      - hc_alpha-postgres
    ports:
      - 4000:4000
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-hc_alpha_db}
      - POSTGRES_HOST=${POSTGRES_HOST:-hc_alpha-postgres}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    env_file:
      - .env
    restart: unless-stopped

  caddy:
    image: caddy:2.3.0
    volumes:
      #- "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy-data:/data/caddy"
      - "caddy-config:/config/caddy"
    ports:
      - ${HTTP_PORT:-8080}:80
      - ${HTTPS_PORT:-8081}:443
    environment:
        SITE_ADDRESS: ${SITE_ADDRESS:-localhost:80}
        APP_ADDRESS: ${APP_ADDRESS:-app:4000}
    restart: unless-stopped
    depends_on:
      - app

volumes:
  caddy-data:
  caddy-config:
